services:
  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      - PGURI=postgres://postgres:secret@database/postgres
    ports:
      - "3000:3000"
  database:
    environment:
      - POSTGRES_PASSWORD=secret
    healthcheck:
      interval: 1s
      test: "pg_isready --username=postgres"
    image: postgres:15
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3000
volumes:
  data:
